development:
  SMTP_USER: "estebanfml@gmail.com"
  SMTP_PASSWORD: "pepapanchadanka"
test:

production:
  SMTP_USER: "estebanfml@gmail.com"
  SMTP_PASSWORD: "pepapanchadanka"
  SENDGRID_PASSWORD:  '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'
  SENDGRID_USER:  'apikey'
